with-expecter: True
disable-version-string: True
log-level: info
packages:

  github.com/JoshuaPangaribuan/common-go/config:
    config:
      all: True
      inpackage: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: "mocks"
      
